// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.8
// source: m_create_goods.proto

package pb_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MCreateGoodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsList []*Goods `protobuf:"bytes,1,rep,name=goods_list,json=goodsList,proto3" json:"goods_list,omitempty"`
}

func (x *MCreateGoodsRequest) Reset() {
	*x = MCreateGoodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_m_create_goods_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MCreateGoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCreateGoodsRequest) ProtoMessage() {}

func (x *MCreateGoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_m_create_goods_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCreateGoodsRequest.ProtoReflect.Descriptor instead.
func (*MCreateGoodsRequest) Descriptor() ([]byte, []int) {
	return file_m_create_goods_proto_rawDescGZIP(), []int{0}
}

func (x *MCreateGoodsRequest) GetGoodsList() []*Goods {
	if x != nil {
		return x.GoodsList
	}
	return nil
}

type MCreateGoodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResp *BaseResp `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
}

func (x *MCreateGoodsResponse) Reset() {
	*x = MCreateGoodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_m_create_goods_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MCreateGoodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCreateGoodsResponse) ProtoMessage() {}

func (x *MCreateGoodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_m_create_goods_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCreateGoodsResponse.ProtoReflect.Descriptor instead.
func (*MCreateGoodsResponse) Descriptor() ([]byte, []int) {
	return file_m_create_goods_proto_rawDescGZIP(), []int{1}
}

func (x *MCreateGoodsResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

var File_m_create_goods_proto protoreflect.FileDescriptor

var file_m_create_goods_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x1a, 0x0c, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x13, 0x4d,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2b, 0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x52, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x44, 0x0a, 0x14, 0x4d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x62, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x61, 0x63, 0x6b, 0x54, 0x4a, 0x43, 0x2f, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x5f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_m_create_goods_proto_rawDescOnce sync.Once
	file_m_create_goods_proto_rawDescData = file_m_create_goods_proto_rawDesc
)

func file_m_create_goods_proto_rawDescGZIP() []byte {
	file_m_create_goods_proto_rawDescOnce.Do(func() {
		file_m_create_goods_proto_rawDescData = protoimpl.X.CompressGZIP(file_m_create_goods_proto_rawDescData)
	})
	return file_m_create_goods_proto_rawDescData
}

var file_m_create_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_m_create_goods_proto_goTypes = []interface{}{
	(*MCreateGoodsRequest)(nil),  // 0: goods.MCreateGoodsRequest
	(*MCreateGoodsResponse)(nil), // 1: goods.MCreateGoodsResponse
	(*Goods)(nil),                // 2: goods.Goods
	(*BaseResp)(nil),             // 3: goods.BaseResp
}
var file_m_create_goods_proto_depIdxs = []int32{
	2, // 0: goods.MCreateGoodsRequest.goods_list:type_name -> goods.Goods
	3, // 1: goods.MCreateGoodsResponse.base_resp:type_name -> goods.BaseResp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_m_create_goods_proto_init() }
func file_m_create_goods_proto_init() {
	if File_m_create_goods_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_m_create_goods_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MCreateGoodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_m_create_goods_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MCreateGoodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_m_create_goods_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_m_create_goods_proto_goTypes,
		DependencyIndexes: file_m_create_goods_proto_depIdxs,
		MessageInfos:      file_m_create_goods_proto_msgTypes,
	}.Build()
	File_m_create_goods_proto = out.File
	file_m_create_goods_proto_rawDesc = nil
	file_m_create_goods_proto_goTypes = nil
	file_m_create_goods_proto_depIdxs = nil
}
